CREATE TABLE tbluser (
	id SERIAL PRIMARY KEY,
	email VARCHAR(120) UNIQUE NOT NULL,
	name VARCHAR(50) NOT NULL,
	contact VARCHAR(15),
	password TEXT,
	country TEXT,
	currency VARCHAR(5) NOT NULL DEFAULT 'INR',
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbltransaction(
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES tbluser(id),
	description TEXT NOT NULL,
	mode VARCHAR(30) NOT NULL,
	amount NUMERIC(15, 2) NOT NULL,
	increment BOOLEAN NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	currentbalance NUMERIC(15, 2) NOT NULL DEFAULT 0
);